### PR TITLE
Circleci project setup

### PR DESCRIPTION
**Pull request by apavlidi**

### CODE REVIEW

**Comment by michaelbromley** [comment]
You guys adding some multi-vendor stuff? Cool :) I guess these PRs were made by accident though? Or are you planning to contribute something back upstream?

**Comment by apavlidi** [comment]
Hello, @michaelbromley yes we are trying to build sth but we are still in the first steps. Yeah sorry for the PRs, they were made by accident :(

**Comment by michaelbromley** [comment]
No worries :) If you need help with your implementation feel free to join our [slack](https://join.slack.com/t/vendure-ecommerce/shared_invite/enQtNzA1NTcyMDY3NTg0LTMzZGQzNDczOWJiMTU2YjAyNWJlMzdmZGE3ZDY5Y2RjMGYxZWNlYTI4NmU4Y2Q1MDNlYzE4MzQ5ODcyYTdmMGU).

**Comment by apavlidi** [comment]
Yes, I've already joined and asked a question ^_^

**Pull request closed without merging**
