### PR TITLE
fix(core): expose enabled field for product in shop api

### PR DESCRIPTION
**Pull request by alexisvigoureux**
# Description

Expose enabled field for product in shop api

# Breaking changes

# Screenshots
Capture d’écran 2023-11-23 à 13 58 18

# Checklist

:pushpin: Always:
- [x] I have set a clear title
- [x] My PR is small and contains a single feature
- [x] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")

:zap: Most of the time:
- [ ] I have added or updated test cases
- [ ] I have updated the README if needed

### CODE REVIEW

**Comment by michaelbromley** [comment]
Hi!

Can you explain the use-case for this? The "enabled" toggle currently means that the given product is _not_ available in the Shop API when set to `true`. So by definition, if a Product can be seen in the Shop API, it _must_ be enabled.

**Comment by alexisvigoureux** [comment]
Hi, here is our use case:
- The product A is available on the shop API. 
- A user adds it to the cart but does not go as far as paying for the order
- We deactivate the product in the back office for any reason
- The user come back few days/hours later to finalize the order
- We want to display a message that the product is no longer available <- the use case based on the « enabled » field of the product. We don't want to delete the cart because it's not great for the UX. The user would not go through the search query but directly from the activeOrder query

Another option: We could disable all the variants when we deactivate a product but that would complicate reactivation (Were all the variants enabled?). This is an option because the productVariant enabled field is available

**Comment by michaelbromley** [comment]
ah ok I see. So this change would not alter the actual ability to access disabled variants at all. It only is relevant in that case where the variant is related to an existing OrderLine.

Looking at the code, I see that currently we would return that `OrderLine.productVariant` regardless of the `enabled` setting (and even if it has been soft-deleted). So in that case yes I see that the `enabled` field gives useful information.

> Another option: We could disable all the variants when we deactivate a product

I'm not understanding how this would solve it - the disabled variants would still be returned with `orderLine.productVariant` even if disabled right?

**Comment by alexisvigoureux** [comment]
> ah ok I see. So this change would not alter the actual ability to access disabled variants at all. It only is relevant in that case where the variant is related to an existing OrderLine.

Exactly, it wouldn't change the way things work now. It's fine to return the variant regardless of the `enabled` setting. We just need to be able to access the `enabled` setting of the product as well as that of the variant, it's a feature rather than a fix.

> I'm not understanding how this would solve it - the disabled variants would still be returned with orderLine.productVariant even if disabled right?

I was proposing another solution, which is to listen to the change of state of the `enabled` setting of the product to deactivate all the variants, but this is more complex and can lead to side effects.

**Comment by alexisvigoureux** [comment]
Did you need any other information? 
The enabled field was already exposed in the admin-api, so we can expose it in the shop-api to access it from the orderLine

**Comment by michaelbromley** [comment]
Hi,

No I think we're good to include this. Can you just make the PR against the `minor` branch though because it's a new feature & API change. I've started publishing pre-releases for the next minor so you'll be able to use it before the final v2.2 release.

**Comment by alexisvigoureux** [comment]
Hi, perfect, it's moved against the minor branch

**Pull request merged**
