### PR TITLE
Fix: add Subscription to parentType

### PR DESCRIPTION
**Pull request by danieldflrss**
Add Subscription to parent type resolver action
fix problem when trying to authenticate a graphql subscription

### CODE REVIEW

**Comment by michaelbromley** [comment]
Hi, thank you for this contribution! You can make this PR against the `minor` branch rather than `major` since it is not a breaking change.

**Comment by chregu** [comment]
Could we get this merged? Or shall I do a new PR against the `master` branch?

**Comment by michaelbromley** [comment]
@chregu yes, do a PR against `master` and I'll merge right away, and plan a release this week.

**Comment by chregu** [comment]
Here you go https://github.com/vendure-ecommerce/vendure/pull/1881

**Pull request closed without merging**
