### PR TITLE
Admin UI rtl with Arabic translation improvements

### PR DESCRIPTION
**Pull request by wpplumber**
This PR is in progress.

### CODE REVIEW

**Comment by wpplumber** [comment]
FYI @michaelbromley, this is not the first use case but to avoid blocking me from going forward in RTL implementation I see to delay the creation of bugs until I'm done. 

image

**Comment by wpplumber** [comment]
I made a first review for most screens and seems ok but until doing more reviews. (Desktop only)

**Comment by wpplumber** [comment]
I made a second review this night and seems ok.

I plan to do other as a final confirmation.

**Comment by wpplumber** [comment]
All 3 reviews done.

**Comment by michaelbromley** [comment]
Thank you so much for your excellent work on this!

**Pull request merged**
