### PR TITLE
fix(admin-ui): Change max height to min height for channel assignment block

### PR DESCRIPTION
**Pull request by monrostar**
# Description

Updated the block height for the Channel block `.channel-assignment`. Because there was a fixed height there, a large number of channels simply did not fit and the button to add new channels was hidden

# Breaking changes

Does this PR include any breaking changes we should be aware of?
* no

# Screenshots
Before
image
After
image

# Checklist

📌 Always:
- [x] I have set a clear title
- [x] My PR is small and contains a single feature
- [x] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")

👍 Most of the time:
- [ ] I have added or updated test cases
- [ ] I have updated the README if needed

### CODE REVIEW

**Comment by monrostar** [comment]
@michaelbromley 

I don't know why this fix hasn't been made yet, but it's so annoying :) 
Even though we don't use this functionality, I would like to see all channels and the button :)

**Comment by michaelbromley** [comment]
Does this still look reasonable with only eg 2 channels assigned? Not too much white space?

**Comment by monrostar** [comment]
> Does this still look reasonable with only eg 2 channels assigned? Not too much white space?
Yeah, that's a good question :) I'll update again

**Comment by monrostar** [comment]
> > Does this still look reasonable with only eg 2 channels assigned? Not too much white space?
> 
> Yeah, that's a good question :) I'll update again

24px will be fine. This is almost minimum

image

**Comment by michaelbromley** [comment]
Thanks!

**Pull request merged**
