### PR TITLE
fix(ui-devkit): pin version

### PR DESCRIPTION
**Pull request by martijnvdbrug**
I tried downgrading to 1.6.2 because of [an issue](https://github.com/vendure-ecommerce/vendure/issues/1685), but my admin kept saying I was running 1.6.4, while I definitely downgraded to 1.6.2 for all my dependencies. Turned out to be the transient dependency `admin-ui`  in `ui-devkit`.

By pinning this version, the ui-devkit will always use its corresponding `common` and `admin-ui` versions, and not the latest patch.

### CODE REVIEW

**Comment by martijnvdbrug** [comment]
@michaelbromley could you try and rerun the tests? I think it's highly unlikely that pinning 2 dependencies causes the e2e to fail...

**Comment by michaelbromley** [comment]
I think this issue is the same as what I discuss in this comment: https://github.com/vendure-ecommerce/vendure/issues/1331#issuecomment-1013226791

In short, this change will get overwritten by Lerna next time we publish a new version.

**Comment by martijnvdbrug** [comment]
The issue does mention that this should work without range prefix, so no `~` or `^` combined with `--exact`. Lerna will still update the dependencies in consuming projects.

Shall I add `--exact` to this PR?

Just tested:
image
Ran `yarn lerna publish --exact`
Result:
image

**Comment by martijnvdbrug** [comment]
@michaelbromley Could this be the result of the lerna `--exact` flag? 
`The Angular CLI requires a minimum Node.js version of either v14.15, or v16.10.` It only fails for windows with node 12.x.

If so, lets close this. Too much hassle for a very small, debatable improvement

**Comment by michaelbromley** [comment]
Hi Martijn,
Thanks for the extra investigation in this one. The `--exact` flag looks promising in this case. I'm just wondering whether there might be any unforeseen effects of switching to exact versions in all Vendure packages now. E.g. if some plugin specifies a peerDependency with a `^` range, and the core packages specify an exact version, could that lead to issues? I think it's very hard to know since the interactions of all those dependencies get really complex pretty quickly.

Let me sit on this one a bit, I need some time to properly investigate. But I'll prioritize that Admin UI issue for the next patch release though :)

**Comment by martijnvdbrug** [comment]
@michaelbromley thanks for the response. I'm also a bit hesitant about any side effects for this one... Let's leave this PR open for reference. Its not a pressing issue for me, I worked around it by adding this to the package.json: 
```json
  "resolutions": {
    "@vendure/admin-ui": "1.6.2",
    "@vendure/common": "1.6.2"
  },
  ```

**Comment by martijnvdbrug** [comment]
Closing this, we can still lookup closed PR's :)

**Pull request closed without merging**
