### PR TITLE
fix(admin-ui): Translate to Spanish all languages available in the languag…

### PR DESCRIPTION
**Pull request by JorgeFPastor**
Translate to Spanish all languages available in the language selection menu.

### CODE REVIEW

**Comment by JorgeFPastor** [comment]
I will provide extensive translation soon.

**Comment by michaelbromley** [comment]
Hi! Thanks for the contribution. Are you intending to provide more translations in _this_ PR or in a separate one? I want to know whether I should merge this now or wait for more.

**Comment by JorgeFPastor** [comment]
Hi! Sorry for the late reply. I will provide more translations in a separate PR.

**Comment by michaelbromley** [comment]
Thanks!

**Pull request merged**
