### PR TITLE
fix: Use default channel in Stripe webhook calls to reach all orders

### PR DESCRIPTION
**Pull request by yasserlens**
… Fixes issue #3072

# Description
Orders can switch channels (e.g., global to UK store), causing lookups by the original channel to fail. Using a default channel avoids "entity-with-id-not-found" errors. See https://github.com/vendure-ecommerce/vendure/issues/3072

# Breaking changes
No

# Screenshots
NA

# Checklist

📌 Always:
- [ ] I have set a clear title
- [ ] My PR is small and contains a single feature
- [ ] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")

👍 Most of the time:
- [ ] I have added or updated test cases
- [ ] I have updated the README if needed

### CODE REVIEW

**Comment by yasserlens** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by yasserlens** [comment]
recheck

**Comment by yasserlens** [comment]
recheck

**Comment by michaelbromley** [comment]
Thank you!

**Pull request merged**
