### PR TITLE
fix(core): use relations argument if supplied

### PR DESCRIPTION
**Pull request by martijnvdbrug**
`ProductService.findOneBySlug(ctx, 'some-slug', ['relations'])` was never using the given relations argument.

### CODE REVIEW

**Comment by martijnvdbrug** [comment]
Pipeline is failing because of NPM being unavailable
image

I believe unrelated to this PR.

**Comment by michaelbromley** [comment]
🤦 looks like I was doing some testing and left the test code in there!

Yeah the CI failure looks like some network flaked out. I'll run again to check.

**Comment by michaelbromley** [comment]
OK now it looks like we have a genuine e2e test failure in the product.e2e-spec file

**Comment by martijnvdbrug** [comment]
Will continue this after july 18. On holiday at the moment...

**Comment by martijnvdbrug** [comment]
@michaelbromley I'm a bit stuck, not sure what is going on:

The `@Relations()` decorator in `product.resolver.ts - product()` is passing the relation `translations` to `productService.findBySlug()` this results in SQLite trying to query the column `product_translations.languageCode`, but the column is called `product_translation.languageCode` (not plural) in my SQLite db.

image

image

So, is this a SQLite bug, or is something wrong with the `@Relations()` decorator?

**Comment by michaelbromley** [comment]
I can reproduce locally. Looking into this now.

**Comment by michaelbromley** [comment]
Closing in favour of #1709

**Pull request closed without merging**
