### PR TITLE
bug(admin-ui): Asset drag/drop support in safari

### PR DESCRIPTION
**Pull request by xxKRASHxx**
**STR:**

1.  custom-built admin-ui, `ts-node compile-admin-ui.ts`:
```
import { compileUiExtensions } from '@vendure/ui-devkit/compiler';
import path from 'path'

compileUiExtensions({
    outputPath: path.join(__dirname, 'dist/admin-ui'),
    extensions: [{
        translations: {
            ru: path.join(__dirname, 'translations/ru.json'),
        }
    }],
}).compile!()
```
2. connect admin-ui plugin in `vendure-config.ts`:
```
AdminUiPlugin.init({
  app: {
    path: path.join(__dirname, 'admin-ui/dist')
  },
  ...
});
```

3. open admin web page from Safari browser 13.0.5

**ART:** 
-  blank page
- https://stackoverflow.com/questions/56137343/angular-not-working-on-safari-browser-but-working-well-on-other-browsers

**ERT:**
- page opens as usual

### CODE REVIEW

**Comment by michaelbromley** [comment]
Hi, thanks for the contribution. I don't understand something: the change in your PR is just a TypeScript type annotation. These are removed during compilation and have no effect on the runtime behaviour of the app.

Could you please post any errors in the console of Safari when you see the blank page?

**Comment by xxKRASHxx** [comment]
Screenshot 2020-03-31 at 19 36 23

**Comment by xxKRASHxx** [comment]
> the change in your PR is just a TypeScript type annotation.
I understand, just followed stackoverflow suggestion...
basically, I not so deep in web & angular so bit confused on how to debug such issues.

**Comment by xxKRASHxx** [comment]
@michaelbromley, I think, we need a polyfill for DragDrop events, not the `any` 😑 ...

**Comment by edxds** [comment]
> Hi, thanks for the contribution. I don't understand something: the change in your PR is just a TypeScript type annotation. These are removed during compilation and have no effect on the runtime behaviour of the app.

Angular actually includes DragEvent as a variable in some type decorators that are actually included in the app bundle. This causes the "can't find variable DragEvent" error. Changing DragEvent to Event is enough to fix the error and doesn't involve using 'any'.

**Comment by michaelbromley** [comment]
@edxds Can you confirm that the change in this PR actually resolves the issue on Safari? I don't have access to Safari locally.

**Comment by edxds** [comment]
This PR seems to fix the issue in Safari.

**Pull request merged**
