### PR TITLE
feat(admin-ui): Add React useLazyQuery hook

### PR DESCRIPTION
**Pull request by alexisvigoureux**
# Description

The aim is to be able to execute a graphql query in response to an event (a click on a button for example). In the same way as we do with useMutation. Today, the useQuery is executed as soon as the React component is loaded, which limits its use.
A complete example of use is available in the code.

More info about useLazyQuery in [Apollo documentation](https://www.apollographql.com/docs/react/api/react/hooks/#uselazyquery)

# Breaking changes

No breaking changes

# How to test
In dev-server/ui-extensions-library/ui/react-components/ReactUI.tsx
Add

```
import {useLazyQuery} from '@vendure/admin-ui/react';

const GET_PRODUCT = gql`
   query GetProduct($id: ID!) {
     product(id: $id) {
       id
       name
       description
     }
   }`;

type ProductResponse = {
    product: {
        name: string
        description: string
    }
}

export function ReactUi() {
const [getProduct, { data, loading, error }] = useLazyQuery<ProductResponse>(GET_PRODUCT);

const handleClick = () => {
        getProduct({
                id: '1',
        }).then(result => {
            // do something with the result
        });
    };

...
return (
...
<Card title="Test useLazyQuery">
                        <div>
                            <button onClick={handleClick} className="btn btn-primary">Get product</button>
                            {data && (
                                <div>
                                    <h1>{data.product.name}</h1>
                                    <p>{data.product.description}</p>
                                </div>)}
                        </div>
                    </Card>
)}
```

# Screenshots

https://github.com/vendure-ecommerce/vendure/assets/6134849/dac7342f-c6a2-43c9-9f5c-ccc88d4733e0

# Checklist

:pushpin: Always:
- [x] I have set a clear title
- [x] My PR is small and contains a single feature
- [x] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")

:zap: Most of the time:
- [ ] I have added or updated test cases
- [x] I have updated the documentation

### CODE REVIEW

**Comment by michaelbromley** [comment]
Thanks, this looks like a nice addition, and good work with the documentation too.

Could you make this against the `minor` branch though since it's a new feature?

**Comment by alexisvigoureux** [comment]
Do you have an estimated date for the next minor release?
I did the PR against the master branch because I was hoping to get it quickly as we're stuck with the way useQuery works. Lost bet. I will change the source branch

**Comment by michaelbromley** [comment]
I understand :) I don't have a date for the next minor but I will start releasing the current minor under the `next` tag soon, because we now have a couple of new features already added.

Another option is to temporarily implement this in your own code. It would be OK to add an `export` to the `useDataService` hook so you can import it into your own code and thus only have a small amount of code to maintain in the mean time.

**Comment by alexisvigoureux** [comment]
export `useDataService` is a good quick win. Thanks for the suggestion, the PR is available [here](https://github.com/vendure-ecommerce/vendure/pull/2502)

**Pull request merged**
