### PR TITLE
feat(search): add to SearchResponse collections array

### LINKED ISSUE #943: Add to SearchResponse collections array
**Is your feature request related to a problem? Please describe.**
Now it's difficult to create UI controls that can allow user to filter search results by collections.

**Describe the solution you'd like**
Add to SearchResponse new fileld "collections", that contain all ids fo collection found in search (analog of facetValues field).
Technically, it will make one more request to search index.

**Describe alternatives you've considered**
Current approach allows to make it only by mapping collections and facet values on storefront side (by collections query) and then calculate found collections in query by facetValues in SearchResponse.

### PR DESCRIPTION
**Pull request by Izayda**
Close #943

### CODE REVIEW

**Comment by michaelbromley** [comment]
Thanks!

**Comment by Izayda** [comment]
Thank you for great product! How often do you merge minor to master?

**Comment by michaelbromley** [comment]
👍 
I will merge minor to master just before making a minor release. I am planning to do so this week. I'm just now working on some other issues that I want to get into the release.

**Comment by Izayda** [comment]
ok, thanks!

**Pull request merged**
