### PR TITLE
chore: Add npm script for Docker

### PR DESCRIPTION
**Pull request by kibertoad**
Simple convenience scripts for managing Docker

### CODE REVIEW

**Comment by kibertoad** [comment]
There is no console output available, but it really looks like a flaky workflow.

**Comment by michaelbromley** [comment]
Yes the CI failure is definitely due to flakiness rather than your changes.

I personally tend to develop against MariaDB, so these scripts are less useful for me being postgres-specific. I tend to use the Docker Desktop app to start and stop containers, since I do a lot of switching around throughout the day depending on what I'm working on and I find it better to control all containers on my machine from a single app.

**Comment by kibertoad** [comment]
Should I adjust script to run more databases or should this PR be closed altogether?

**Comment by michaelbromley** [comment]
I'd say close it in service of keeping the npm script count smaller. But thanks for your willingness to contribute!

**Comment by kibertoad** [comment]
Roger!

**Pull request closed without merging**
