### PR TITLE
feat(admin-ui): Add rtl compatibility to some admin-ui components

### PR DESCRIPTION
**Pull request by HoseinGhanbari**
`ModalDialogComponent` is now supporting dynamic direction (ltr/rtl) based on the `language` & `locale` provided by  `dataService`.

### CODE REVIEW

**Comment by HoseinGhanbari** [comment]
`DropdownMenuComponent` is now supporting dynamic direction (ltr/rtl) based on the `language` & `locale` provided by `dataService`.

**Comment by HoseinGhanbari** [comment]
`ThemeSwitcherComponent` is now compatible with rtl layouts.

**Comment by HoseinGhanbari** [comment]
`NotificationComponent` is now supporting dynamic direction (ltr/rtl) based on the `language` & `locale` provided by `dataService`.

**Comment by HoseinGhanbari** [comment]
`NotificationService`'s unit tests using `ng test` can now be completed successfully without any failures.

**Comment by michaelbromley** [comment]
Hi,
Thanks for this contribution! I have an idea about how we can simplify this: the current ui language is always stored in local storage and thus it should be possible to be retrieved from the affected components using:

```ts
export class NotificationComponent implements OnInit {
  direction: 'ltr' | 'rtl';

  constructor(private localStorageService: LocalStorageService, private i18nService: I18nService) {
    this.direction = this.i18nService.isRTL(this.localStorageService.get('uiLanguageCode');
  }

}
```

Can you try to refactor like this and see if that works? That would cut down on the amount of code we need to add quite significantly.

**Comment by HoseinGhanbari** [comment]
Yeah, I'll give it a shot. but I think there may be cases that setting the direction inside constructor wouldn't take effect when user try change the locale/language at runtime/asynchronously. Actually we have to update the `direction` based on the user interactions and on an observable basis. I will keep you updated. But let me know if you are ok with setting `direction` inside constructor.

Also note that, as an alternate solution, we can create some sort of `BehaviorSubject` on a shared service that every component which requires awareness of current `ltr` / `rtl` status can subscribe and do the rest inside their `ts` file.

**Comment by HoseinGhanbari** [comment]
Thank you for your reply. I will soon update the strategy on accessing `direction`, refactor the whole changes and keep you updated. 🚀

**Comment by HoseinGhanbari** [comment]
- new `LocalizationService` with its minimal unit test has been added.
- both `uiLanguageAndLocale$` & `direction$` has been moved to `LocalizationService`.
- new shared types called `LocalizationLanguageCodeType` & `LocalizationDirectionType` has been extracted.
- all usages of `uiLanguageAndLocale$` & `direction$` is now referencing `LocalizationService`.
- small `scss` & `autoprefixer` warning related to `theme-switcher.component.scss` has been resolved.
- access to `ltr/rtl` status is now as easy as the following.
```ts
import { LocalizationDirectionType, LocalizationService } from '../../providers/localization/localization.service';

export class NotificationComponent implements OnInit {
    direction$: LocalizationDirectionType;

    constructor(private localizationService: LocalizationService) { }

    ngOnInit(): void {
        this.direction$ = this.localizationService.direction$;
    }
}
```

**Comment by michaelbromley** [comment]
Beautiful refactor, thank you!

**Comment by HoseinGhanbari** [comment]
Its my pleasure! 👌

**Pull request merged**
