### PR TITLE
fix(core): update orderLine on applyPriceAdjustments

### PR DESCRIPTION
**Pull request by ankitdev10**
# Description

This patch fixes applyPriceAdjustment method for updated order lines.

# Breaking changes

Does this PR include any breaking changes we should be aware of?

NO

# Screenshots

You can add screenshots here if applicable.

# Checklist

📌 Always:
- [x] I have set a clear title
- [x] My PR is small and contains a single feature
- [x] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")

👍 Most of the time:
- [x] I have added or updated test cases
- [x] I have updated the README if needed

### CODE REVIEW

**Comment by JamesLAllen** [comment]
I'm not sure how this is any different from how it currently works, is it returning a different result?

```const updatedOrder = await this.orderCalculator.applyPriceAdjustments(
            ctx,
            order,
            promotions,
            updatedOrderLines ?? [],
        )```

The way I read this, `updatedOrder.lines` would equal `updatedOrderLines` or `[]`, right?

**Comment by ankitdev10** [comment]
Yes, it was not working for some reason but it did when I changed exact those patched lines in this commit directly in my node_modules. I have a customField for discount on orderLines and i was using **applyPriceAdjustments** to trigger **OrderItemPriceCalculationStrategy** for price recalculation. 

To further extend, price was not updated in order_line table as well. And it works now after those changes.

**Comment by michaelbromley** [comment]
Hi,

It is not clear to me what the exact error is that is being fixed by this PR. Would you be able to describe the issue in more detail?

- What you did
- What the expected result was
- What the actual (erroneous) result was

**Comment by ankitdev10** [comment]
Hello,

So, all I was trying to do was add a customField for discount amount on orderLine because the discount depends upon the exemptions file uploaded by the customer. Admin will later apply the discount and the order price will be recalculated once discoutn is applied. I was failing to trigger price recalculation and while looking into **applyPriceAdjustments**  I had doubt that updated order lines are not saved correctly. All these despite **OrderItemPriceCalculationStrategy** getting triggered correctly. 
[here](https://discord.com/channels/1100672177260478564/1203025235025068092/1203773740798836736)  is the link for this disccusion on help thread in vendure discord server

**Comment by michaelbromley** [comment]
Hi,

the scenario you describe sounds quite complex and I think I'd need to see an actual minimal reproduction in order to properly appreciate it.

**Comment by BijanRegmi** [comment]
So in this loop https://github.com/vendure-ecommerce/vendure/blob/3dfb2d196f31b4277355fee0220054008780bc34/packages/core/src/service/services/order.service.ts#L1687-L1719 all the modification to the orderLine is applied to the `updatedOrderLines` parameter object. This mutated `updatedOrderLines` object is never assigned to `order.lines` so when saving `order.lines` as in here https://github.com/vendure-ecommerce/vendure/blob/3dfb2d196f31b4277355fee0220054008780bc34/packages/core/src/service/services/order.service.ts#L1733 the changes made to the `updatedOrderLines` won't be saved to the db. 


If you follow the call to `this.orderCalculator.applyPriceAdjustments` https://github.com/vendure-ecommerce/vendure/blob/3dfb2d196f31b4277355fee0220054008780bc34/packages/core/src/service/helpers/order-calculator/order-calculator.ts#L49-L106 you will find that the `updatedOrderLines` is never assigned to `order.lines`. Hence any changes made to orderLine is lost when you just save `order.lines`.

**Comment by michaelbromley** [comment]
Thanks for the extra explanation.

> So, all I was trying to do was add a customField for discount amount on orderLine because the discount depends upon the exemptions file uploaded by the customer.

Can you please show me the actual code implementation of this part - I don't fully understand what is going on here.

**Comment by BijanRegmi** [comment]
https://github.com/BijanRegmi/vendure-price-issue

Here's a minimal reproduction steps with a failing test case.

**Comment by michaelbromley** [comment]
I'm going to close this as it became stale and I didn't manage to get my head around the issue it was solving. If a problem still exists, you can open a new PR but please include a test that fails before the change, and passes after it.

**Pull request closed without merging**
