### PR TITLE
perf(core): Refactor applyCollectionFiltersInternal method to improve performance

### PR DESCRIPTION
**Pull request by monrostar**
# Description

I updated the applyCollectionFiltersInternal method to optimize the handling of more variants and also added updating collections only for changed variants if the product has been updated.

Related issue: https://github.com/vendure-ecommerce/vendure/issues/2733

# Breaking changes

Does this PR include any breaking changes we should be aware of?
* no

# Screenshots

You can add screenshots here if applicable.
* no

# Checklist

📌 Always:
- [x] I have set a clear title
- [x] My PR is small and contains a single feature
- [x] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")

👍 Most of the time:
- [ ] I have added or updated test cases
- [ ] I have updated the README if needed

### CODE REVIEW

**Comment by monrostar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by monrostar** [comment]
done

**Comment by monrostar** [comment]
I also added a connection that should only target the master because we don't have context in that location and can't use a transaction. To safely get the correct data after a collection update if replicas are used

**Comment by michaelbromley** [comment]
Thank you! I did some testing locally on a dataset with 13k variants and 300 collections.

before: average 2:28m & 1,460mb
after: average 2:05 & 500mb (only slightly higher than baseline)

**Pull request merged**
