### PR TITLE
feat(admin-ui): Add ability to filter promotions by name or coupon code

### PR DESCRIPTION
**Pull request by dkostenko-jsninja**
Changes in this pull request will allow users to filter promotions by name or coupon code.

### CODE REVIEW

**Comment by michaelbromley** [comment]
Thank you for this contribution!

I do intend to merge this but I am going to wait until after the v1.0.0 release which is planned next week.

**Comment by michaelbromley** [comment]
Hi, I've introduced some new branch conventions to better manage version development. Would you be able to make this PR against the `minor` branch rather than `master`?

**Comment by dkostenko-jsninja** [comment]
Hello! Yes, sure, I've just changed the branch.

**Comment by michaelbromley** [comment]
Thank you, very nice work!

**Pull request merged**
