### PR TITLE
feat(translation): Added nepali translation

### PR DESCRIPTION
**Pull request by BeepLoveKarki**

### CODE REVIEW

**Comment by michaelbromley** [comment]
Thanks! I noticed there are quite a few tokens not translated - 78% have been, but the entire "common" namespace is missing. Are you planning to do a 100% translation?

**Comment by BeepLoveKarki** [comment]
Sure. We will be doing it.

**Comment by michaelbromley** [comment]
OK, let me know when it is done and I can merge.

**Comment by BeepLoveKarki** [comment]
@michaelbromley its ok now. 97%. Its max we can do in Nepali language.

**Pull request merged**
