### PR TITLE
feat(admin-ui): Add some new ltr/rtl compatibility

### PR DESCRIPTION
**Pull request by HoseinGhanbari**

### CODE REVIEW

**Comment by michaelbromley** [comment]
Thanks for the fix! Could you make this PR against the `master` branch instead? I'd consider it more as a fix so it can go in the next patch release.

**Comment by HoseinGhanbari** [comment]
Yeah OFC👌I will soon update the PR.

**Comment by HoseinGhanbari** [comment]
Target branch has been changed from `minor` to `master`.

**Comment by michaelbromley** [comment]
Thank you!

**Comment by HoseinGhanbari** [comment]
I'm so glad it was helpful 👌

**Pull request merged**
