### PR TITLE
feat(elasticsearch-plugin): provide the ctx for custom mappings

### PR DESCRIPTION
**Pull request by mcfedr**
# Description

Given custom mapping access to the ctx, so they can add channel specific data

# Breaking changes

No

# Screenshots

N/A

# Checklist

:pushpin: Always:
- [x] I have set a clear title
- [x] My PR is small and contains a single feature
- [x] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")

:zap: Most of the time:
- [ ] I have added or updated test cases
- [ ] I have updated the README if needed

### CODE REVIEW

**Comment by michaelbromley** [comment]
Hi @mcfedr - nice to hear from you, it has been a while!

This PR is a good additional - please just make it against the `minor` branch as it is a new feature 👍

**Comment by mcfedr** [comment]
@michaelbromley updated the target branch

**Comment by michaelbromley** [comment]
Thank you!

**Comment by mcfedr** [comment]
@michaelbromley any chance we could get a release with this?

**Comment by michaelbromley** [comment]
@mcfedr I just published v2.2.0-next.0 👍

**Pull request merged**
