### PR TITLE
feat(email-plugin): Allow currencies with formatMoney helper

### LINKED ISSUE #2530: Allow currency and locale with the `formatMoney` helper
**Is your feature request related to a problem? Please describe.**
Emails should list the prices for products, along with their currencies

**Describe the solution you'd like**
The `formatMoney` function to accept a currency and optional locale, so it all doesn't have to be hardcoded.

**Describe alternatives you've considered**
Hardcoding, which is not very scalable since we shouldn't reinvent the wheel (i.e. what `Intl` has done for us).

### PR DESCRIPTION
**Pull request by StampixSMO**
# Description

Added 2 new parameters to the `formatMoney` helper: currency and locale

Closes #2530

# Breaking changes

Does this PR include any breaking changes we should be aware of?
No

# Checklist

:pushpin: Always:
- [x] I have set a clear title
- [x] My PR is small and contains a single feature
- [x] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")

:zap: Most of the time:
- [x] I have added or updated test cases
- [x] I have updated the README if needed

### CODE REVIEW

**Comment by StampixSMO** [comment]
MacOS CI failing doesn't look to be related to this PR

**Comment by michaelbromley** [comment]
Thanks, this is a long-overdue feature! 

Everything looks good - nice work on the docs and tests 👍

I think it would also make sense to update the [default order confirmation template](https://github.com/vendure-ecommerce/vendure/blob/15f9b44fba0c31aa8ad932ec268b33f4a6925e52/packages/email-plugin/templates/order-confirmation/body.hbs#L104) to use the correct currencyCode too. Would you like to include that in this PR too?

**Comment by StampixSMO** [comment]
> I think it would also make sense to update the [default order confirmation template](https://github.com/vendure-ecommerce/vendure/blob/15f9b44fba0c31aa8ad932ec268b33f4a6925e52/packages/email-plugin/templates/order-confirmation/body.hbs#L104) to use the correct currencyCode too. Would you like to include that in this PR too?

Yep, missed that. Done!

**Comment by michaelbromley** [comment]
The test output indicates that the `onSend` mock function is not being called as expected for some reason. This part:

```
onSend.mock.calls[0][0].body
```
means "the first argument of the first call to `onSend`".

**Comment by StampixSMO** [comment]
> The test output indicates that the `onSend` mock function is not being called as expected for some reason. This part:
> 
> ```
> onSend.mock.calls[0][0].body
> ```
> 
> means "the first argument of the first call to `onSend`".

Yep, my bad, I thought that issue was not due to my changes but it definitely was. The helper function threw an error and that was silently failing. All good now!

**Comment by StampixSMO** [comment]
> > The test output indicates that the `onSend` mock function is not being called as expected for some reason. This part:
> > ```
> > onSend.mock.calls[0][0].body
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > means "the first argument of the first call to `onSend`".
> 
> Yep, my bad, I thought that issue was not due to my changes but it definitely was. The helper function threw an error and that was silently failing. All good now!

E2E tests seem to throw `Error: listen EADDRINUSE: address already in use :::3012`, which I'm pretty sure is not related to this PR?

**Comment by michaelbromley** [comment]
> EADDRINUSE: address already in use :::3012

Yes that's just an intermittent flakiness of the e2e tests when 2 test suites running in parallel try to listen on the same port. This all looks good now, thanks for your contribution!

**Pull request merged**
