### PR TITLE
fix(admin-ui): Fix customField product error: handle undef. case

### PR DESCRIPTION
**Pull request by lsimone**
Hello @michaelbromley , this fixes an error that appears when you land on `product detail` admin page

### CODE REVIEW

**Comment by michaelbromley** [comment]
Hi,

I'm having trouble figuring out what particular error this PR is fixing. Can you describe the circumstances that produce the error, and what error message you see?

**Comment by michaelbromley** [comment]
Is this OK to close?

**Comment by lsimone** [comment]
> Is this OK to close?

Sorry I didn't see your first comment.
This PR has been done since if `currentTranslation.customFields` is undefined, the current code will throw an error, while my modification checks this case (and solved my issue).

**Comment by michaelbromley** [comment]
Ok thanks. I took a closer look and could see the issue with accessing the property of undefined.

**Pull request merged**
