### PR TITLE
Custom Payment Process

### PR DESCRIPTION
**Pull request by ekoto4**
Issue #426

# 📌 Overall tasks
* [x]  Adjust Payment state machine to allow for custom states and hooks
* [x]  Add a mutation in Admin GQL to transit to/from Payment state
* [ ]  Add E2E tests

## ⚠ Failed E2E Tests
N/A

### e2e/fulfillment-proccess.e2e-spec.ts
For `transitionPaymentToState` mutation and `CustomPaymentProcess`

#### CustomPaymentProcess
* [ ]  it CustomPaymentProcess should be injectable
* [ ]  it should replace transition target
* [ ]  it custom onTransitionStart handler should return false
* [ ]  it custom onTransitionStart handler should return error message
* [ ]  it custom onTransitionStart handler allows transition'
* [ ]  it should compose multiple CustomOrderProcesse's

#### e2e/order.e2e-spec.ts | e2e/order-channel.e2e-spec.ts
* [ ]  it creates fulfillment with remains items
* [ ]  it transits the first fulfillment from created to shipped and automatically change the order state to partially shipped* [x]  it transits the second fulfillment from created to shipped and automatically change the order state to shipped
* [ ]  it transits the first fulfillment from shipped to delivered and change the order state to partially shipped
* [ ]  it transits the second fulfillment from shipped to delivered and change the order state to shipped

### Other tests
* [x]  Check for Payment nextStates field
* [x]  Check for ORDER_PAYMENT_TRANSITION history in tests

### CODE REVIEW

**Comment by jonyw4** [comment]
Any updates in this PR?

**Comment by ekoto4** [comment]
> Any updates about this PR? I can give some help if you want 😄

Yeah I've been abit busy but I think most of its there. Just need to test it out and write tests. Please feel free to join! Otherwise, I think I can get to it this weekend.

**Comment by ekoto4** [comment]
@michaelbromley I should be able to finish this up this week. If I could get some guidance on the tests needed and where that would be really appreciated.

**Comment by michaelbromley** [comment]
Hi @ekoto4! That's good news.

Regarding e2e tests, I recommend you take a look at [order-process.e2e-spec.ts](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/e2e/order-process.e2e-spec.ts) as many of the tests will be similar, and you can use the same method to test that the transitions are being called as expected (`transitionStartSpy` etc). You can create a new spec file, payment-process.e2e-spec.ts, to house these tests.

**Comment by michaelbromley** [comment]
Hi @ekoto4, I intend to include these features in the upcoming v1.0 release. Since this will be a breaking change, I'd like to get it completed in the next 1-2 weeks so I can begin pre-releases which include all breaking changes.

Please let me know if you intend to complete your planned work in that time frame. If no, that's no problem, I'll finish it up myself.

**Comment by michaelbromley** [comment]
@ekoto4 I'm going to take over this one now. Thank you very much for the work you've done so far!

**Comment by ekoto4** [comment]
@michaelbromley Apologies - Glad to see you were able to pick it up! You've really done well with vendure.

**Pull request merged**
