### PR TITLE
feat(admin-ui): Channel aware picker

### PR DESCRIPTION
**Pull request by casperiv0**
# Description

Allows us to select multiple channels when assigning stuff to channels. Picked up from #2380 

# Breaking changes

Not really, just a different way of changing the UI 

# Screenshots

image

# Checklist

📌 Always:
- [x] I have set a clear title
- [x] My PR is small and contains a single feature

Closes https://github.com/vendure-ecommerce/vendure/issues/2377

### CODE REVIEW

**Comment by casperiv0** [comment]
The publish install CI run seems to have timedout, not sure if it's related to this PR or not.

**Comment by michaelbromley** [comment]
Those jobs are kinda flaky sometimes. The fact that all the other ones pass means it's likely nothing to worry about. Thank you for the PR, I'll review it soon!

**Comment by michaelbromley** [comment]
Thank you! This is really good work. I've merged this manually into the `minor` branch (https://github.com/vendure-ecommerce/vendure/commit/145af00be3ff3b55733b8c71acac32e078ac882b) because it's more of a new feature than a fix. It'll be available soon in v2.2.0.

**Comment by casperiv0** [comment]
Awesome! Thank you 🚀!!

**Pull request closed without merging**
