### PR TITLE
Adding Spanish (ES) translation.

### PR DESCRIPTION
**Pull request by agustif**
Added .vscode/ to .gitignore to avoid committing a file my VS-Code plugin automatically generates to give colors to sidebars, lol

Also don't know where the .whitesource comes from, but you can ignore those 2 edits, the important parts are the es.json files (Y)

Everything is translated! did my best with accents and whatnot ;)

### CODE REVIEW

**Comment by agustif** [comment]
Yayy, it passed the travis build!

**Comment by michaelbromley** [comment]
Wow that was fast!

Do you know how to amend the pull request to remove the whitesource file? That would be a bit cleaner.

**Comment by agustif** [comment]
> Wow that was fast!
> 
> Do you know how to amend the pull request to remove the whitesource file? That would be a bit cleaner.
> 
> edit: You say you don't know where is comes from - do you mean it is not there on your local file system and you didn't check it in to the repo yourself?

Yeah, it's not from my local repo, it's a bot I've enabled on GitHub Marketplace which automatically inserts itself on new repo's I create (it seems), I will disable it and re-do the PR and hope it doesn't fire again

It's like renovate or other GitHub plugins that checks for vulnerabilities in the package.json deps and node modules deps

**Comment by agustif** [comment]
> Wow that was fast!

Yeah well, it was the unsexy thing to do, so better to take it out first of the TODO list...
I actually did it while watch/listening the NestJS presentation video, cool stuff! thinking about using it myself now haha

I will resend a new PR once I disable the culprit extension so it doesn't get side-hacked and added by it's bot (Y)

**Comment by agustif** [comment]
OK so I disabled the WhiteSource extension, pulled master, deleted the .whitesource file and commited back, now it seems fine if you don't mind the .gitignore addition of .vscode/

**Comment by michaelbromley** [comment]
Woohoo! First PR merged! 🎉

**Comment by agustif** [comment]
Hope the next to come are more useful though! hahaha. Hey it's something kinda useful at least, if you're a spanish speaker lol!

**Pull request merged**
